### ISSUE TITLE
Hello I'm struggling with memory management and I'd like some assistance/guidance

### ISSUE THREAD

**Issue by allisoneer** [getty-zig/json#54]
### Description

I'm new to zig and manual memory management in general so please bear with me in case this is a noob question. 

Basically I'm at a point where I'm getting a memory leak or a segmentation fault and I only see one way to fix it and that isn't possible with raw getty/json.

Here is the basis of my code:
 ```zig
 pub fn main() !void {
 
 
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer std.debug.assert(gpa.deinit() == .ok);
    const allocator = gpa.allocator();
    
    const apiInput = CustomInputStruct{};
    
    // this serialization works great.
    const input_json = try json.toSlice(allocator, apiInput);
    defer allocator.free(input_json);
    
    const response = try apiRequest(input_json);
    std.debug.print("The API response was: {}\n", .{response});
}
 
 fn apiRequest(json_payload: []const u8) !CustomResponseStruct {
     // do all http client stuff needed for initialization(auth, variables, allocator, etc)
     var request = try client.open(.POST, uri, headers, .{});
     // do the JSON writing and wait for response. 
     
    // Read the entire response body, but only allow it to allocate 16KB of memory.
    const body = request.reader().readAllAlloc(allocator, 16384) catch unreachable;
    defer allocator.free(body);

    if (json.fromSlice(allocator, CustomResponseStruct, body)) |response| {
        //defer response.deinit();
        return response.value;
    } else |err| {
        std.debug.print("Error unmarshalling JSON Response.\n", .{});
        std.debug.print("Here is the response body: {s}\n", .{body});
        return err;
    }
 }
 ```
 
 In that form of the code, I will be able to print the response successfully but I will get a memory address leak after it prints which completely makes sense. So from looking at the codebase I try to use `deinit()` on the `getty.Result` in order to properly handle the memory.
 
 ```zig
 // ...
     if (json.fromSlice(allocator, CustomResponseStruct, body)) |response| {
        // WE ARE NOW running .deinit().
        defer response.deinit();
        return response.value;
  // ...
 ```
 
 I now get a segmentation fault. Which I think also makes sense because the defer deinit is executed in the scope of the `apiRequest` function and yet I'm attempting to utilize the memory in the main function. 
 
 I then tried to pass an `allocator` from the `main` function to the `apiRequest` function instead of creating a new one inside of `apiRequest` thinking/hoping that maybe that will fix the scoping issue and I will no longer get a segmentation fault. However, that resulted in the same behavior for both above examples but with seemingly more complexity.
 
 I'm starting to wonder if I should simply be returning a `getty.de.Result` type from my `apiRequest()` function so that I can `defer result.deinit()` inside of `main()`, but that leads me to why I am making this issue. It seems that `getty/json` doesn't export any of the deserialization types, and that I'd need to have a dependency for both getty and json and import them separately to get access to using that type in my codebase which seems inherently wrong to do. 
 
 I think if someone who knows what they're doing reads this then They'll be able to send me on my way with whatever the correct solution is(handling memory properly somehow differently than I am now, exporting types in json library, importing getty + json, or only importing getty and using it for everything). Also please tell me if I should be handling errors differently/better somehow. 

### How to Reproduce the Bug

Detailed above

**Comment by phan-do** [comment]
> I'm starting to wonder if I should simply be returning a getty.de.Result type from my apiRequest() function so that I can defer result.deinit() inside of main() [...]

Correct! Returning a `getty.de.Result` from `apiRequest` would be the best option. In general, one should think in terms of `Result`s instead of direct values whenever using functions like `fromSlice`.

Note that I'm planning on adding leaky variants of `fromSlice` to `getty-json`, which should let you avoid having to import `getty`. It'll work the same as `fromSlice` but instead of returning a result it returns a direct value. So you can, for instance, pass an arena allocator to `apiRequest` from `main` and clean up the returned value with a single `deinit` call in `main`.

Technically, you can also pass an arena to `apiRequest` right now to fix your problem, but without the leaky version of `fromSlice`, `getty` will end up creating nested arenas, which is fine but idk if you're okay with any overhead it might cause.

>  It seems that getty/json doesn't export any of the deserialization types, and that I'd need to have a dependency for both getty and json and import them separately to get access to using that type in my codebase which seems inherently wrong to do.

I do understand the concern here of having to import `getty` just for `Result` but consider that:

1. `getty/json` is for JSON-specific logic, while `getty` is for general (de)serialization concerns. The `Result` type works across any data format you deserialize from, so imo it makes sense that it lives in `getty` and not `getty-json`; there's nothing really JSON-centric about it.
2. If you want to do any custom deserialization (which is a pretty common thing to do), you'll be importing `getty` anyways for the `Visitor` interface.
3. I'd rather not encourage re-exporting in (de)serializer libraries since it could wind up being inconsistent and an extra burden for those libraries. Better to just have one export in `getty`, imo.

---

> I then tried to pass an allocator from the main function to the apiRequest function instead of creating a new one inside of apiRequest thinking/hoping that maybe that will fix the scoping issue and I will no longer get a segmentation fault. However, that resulted in the same behavior for both above examples but with seemingly more complexity.

fyi, passing an allocator to `apiRequest` will indeed not fix your issue. However, it _is_ idiomatic Zig and you should probably be doing it anyways. Any function that can potentially allocate takes an allocator parameter in Zig, by convention.

**Comment by allisoneer** [comment]
Thank you very much for the detailed response. I'm well on my way now(both to my (de)serializer goals and an idiomatic codebase :P)!

**Comment by phan-do** [comment]
@AdjectiveAllison The following versions of `getty` and `getty-json` add support for leaky deserialization:

- `getty`: [0074401](https://github.com/getty-zig/getty/commit/00744015f18f2ff02860ef8729ec63e1a157ff26)
- `getty-json`: [783e3f9](https://github.com/getty-zig/json/commit/783e3f9ccdbe08ba63151394362ab6774783f1d4)
